### ISSUE TITLE
With Demarcate 1.1.4 [REMOVED URL]slideshows is dead.

### ISSUE THREAD

**Issue by ericop** [will-hart/demarcate.js#35]
Hi Will,
  Today I came across your great work and wanted to give markdown to presentation a try. Chrome, Firefox and IE9 all can't render [REMOVED URL] . Not sure what underlying piece is broken, but thought I'd let you know.

Keep up the good work sir!

**Comment by will-hart** [comment]
Thanks for the report - looks like this issue is unrelated to demarcate.js... its in the textr code base (which is a Python web app).

From what I can tell it should be a relatively quick fix, I'll have a look on the weekend...

**Comment by will-hart** [comment]
@ericop - Should be sorted now - a very simple javascript fix in the end! 

Thanks for raising the issue.

**Comment by ericop** [comment]
Sorry I got the wrong code base, but glad you were able to fix it. Looks good now!
